### ISSUE TITLE
Massive thread consumption when tens of thousands of connected clients (OOMs)

### ISSUE THREAD

**Issue by troyunverdruss** [cettia/cettia-java-server#19]
We have been using this library in production and under extreme load (tens of thousands of connected clients) our services were OOMing. Tracked it down to thread pools being created in the DefaultServer.DefaultServerSocket code where it creates a new scheduled thread pool for every connection. 

I've submitted a PR that fixed this issue for us in production, some additional notes in the PR but basically it creates a pool of workers that are shared and a scheduled executor that handles starting everything. PR is here: #18 

We saw this in both a beta version we were using and the current 1.0 version (implementation hasn't changed between the two).

**Comment by flowersinthesand** [comment]
@troyunverdruss I am sincerely sorry for the late response. In my defense, after releasing Cettia 1.0.0 RC on Jun 2017, my company initiated new outsourcing business model under the vision of "Startup for Startup". Because it was my idea, I couldn't have enough time for open source projects.

Anyway, I'm really glad you've used Cettia in your production service but here're practical proposals.

1. Use [Atmosphere](https://github.com/atmosphere/atmosphere) by jfarcand instead of Cettia. When you are in trouble, you can ask help from http://async-io.org/ which powers Atmosphere. jfarcand used to be my boss so I have no doubt he can save you from any troubles.
1. Be the contribtutor of Cettia. I think the value of open source software is basically simply to help someone so it's natural that someone like you who adopted this project for your production service drive this project.

I'll review #18 and get back to you weekend.

Also, it would be better for you to use GA not just Beta or RC IMO. Just tell me if you want GA. I'm all for releasing 1.0.0 GA.

**Comment by flowersinthesand** [comment]
I've just merged #18 and committed e69b498a5886244cdf9d745476cf8d810f09f4c2.

Thanks for your awesome contribution to Cettia again! It would be really nice if you can share your experience in using Cettia at https://groups.google.com/forum/#!forum/cettia 🙏

**Comment by jfarcand** [comment]
The current solution won't scale either BTW ;-) For 5000 connections, 5000 threads will be created by the `Executor` returned by the `newCachedThreadPool`. So in prod you will hit the same problem!

**Comment by troyunverdruss** [comment]
Actually, that's not exactly accurate. In the old solution there was a dedicated scheduled thread for each connection. That thread's job was to send a heartbeat every 20s and a termination event 60s after the client is gone (or when it's disconnecting, I can't remember). Those operations, in sum, take milliseconds but the thread still sits there idle for the remainder of each minute. 

In the new solution, the cached thread pool is shared among all the connected clients and instead of any single thread sitting idle, it will be reused for an additional client (and terminated when no work is available). So when you have 100 connected clients, they might be serviced by a single cached thread or thereabouts (each client filling in where the old thread used to be idle) whereas before that would require 100 individual, mostly idle, threads.

In practice, I saw our thread usages drop from 10-20k+ (mostly idle) threads to ~10 (very active) in our production environment.

**Comment by jfarcand** [comment]
@troyunverdruss True, but you should use a bounded thread pool as `newCachedThreadPool` can still grow forever....

**Comment by troyunverdruss** [comment]
True - but that was the original design so I didn't want to change that without knowledge of how this was used in the wild. At least now it can handle orders of magnitude more traffic than it could before.

**Comment by flowersinthesand** [comment]
@jfarcand @troyunverdruss I'm all for changing the original design as long as API is compatible so please ask me anything. As you experienced, scheduling heartbeat and delete event timer is all.

BTW, there's similar implementation in https://github.com/cettia/cettia-java-server/blob/master/server/src/main/java/io/cettia/transport/http/HttpTransportServer.java#L392 Do you think it should be reimplemented like your work using Executors.newSingleThreadScheduledExecutor and Executors.newCachedThreadPool?
